# Generated by Django 6.0 on 2026-01-26 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstAppDrf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_works', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
