# Generated by Django 6.0 on 2026-02-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstAppDrf', '0003_appointmentdesicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdesicion',
            name='comment',
        ),
    ]
