# Generated by Django 6.0 on 2026-02-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstAppDrf', '0004_remove_appointmentdesicion_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdesicion',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
